### PR TITLE
pull arch rebuild packages from pinnings text file

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
I think this is failing because the file doesn't exit yet (pending https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/356)

**Comment by CJ-Wright** [comment]
@regro/auto-tick

**Comment by ocefpaf** [comment]
> I think this is failing because the file doesn't exit yet (pending [conda-forge/conda-forge-pinning-feedstock#356](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/356))

Any reason to not do both in a single PR?

**Comment by CJ-Wright** [comment]
> Any reason to not do both in a single PR?

They are in two different repos, can I do multi-repo/multi-org PRs?

**Comment by ocefpaf** [comment]
> They are in two different repos, can I do multi-repo/multi-org PRs?

Sorry. I clicked to early on the comment button. What I meant is on the edit above.

**Comment by CJ-Wright** [comment]
I think we've been pretty good about exposing migrations to people via the pinning repo. I'd like to continue that trend so we can get better engagement. Also I like having the "what I want" and "how does that get done" split between this and pinnings.

**Comment by CJ-Wright** [comment]
This is failing because the file layout of travis is a bit different than the file layout in production. The tests are run from their own dir rather than inside the cf-graph-countyfair dir.

**Comment by scopatz** [comment]
Does that mean that it is OK to merge?

**Comment by CJ-Wright** [comment]
maybe? I'll merge tomorrow and see how it goes.

**Comment by scopatz** [comment]
This has conflicts now

**Pull request closed without merging**
