### PR TITLE
more compact grpah

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@regro/auto-tick

**Comment by mbargull** [comment]
The graphs would still be rather wide and not fit well with the columnar viewport on the status page, right?

Maybe a simpler alternative:
```diff
-    gv = graphviz.Digraph()
+    gv = graphviz.Digraph(graph_attr={"packmode": "node"})
```
at https://github.com/regro/cf-scripts/blob/c2f6f7ca38522f9364438cb3d7961ffb093ef8ea/conda_forge_tick/auto_tick.py#L505.

If that's "too busy", `"packmode": f"array_{n}"` (with `n=3` maybe) could work.

Or (IDK if that works): Acc. to http://www.graphviz.org/doc/info/attrs.html#d:margin you could set `margin` for "clusters" to increase the space between connected components if you put the connected components in their own "cluster" subgraphs and use `"packmode": "cluster"`.

**Comment by CJ-Wright** [comment]
PRs welcome!

**Comment by mbargull** [comment]
> PRs welcome!

I kinda expected (not hoped) for that answer ;P.

I only need to clone this one, countyfair, and pinning repos to try it out, right?

**Comment by CJ-Wright** [comment]
Sorry!

yes, countyfair and pinning need to live at the same level
```
top_dir
-- countyfair
-- pinning
```

**Pull request merged**
