### PR TITLE
ENH add parsing function

### PR DESCRIPTION
**Pull request by beckermr**
cc @CJ-Wright

### CODE REVIEW

**Comment by beckermr** [comment]
Here is an example of how to use it:

```python
In [1]: from conda_forge_tick.utils import parse_meta_yaml_to_outputs_dicts                                                                                               
/Users/beckermr/miniconda3/lib/python3.7/site-packages/github3/session.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Callable
/Users/beckermr/miniconda3/lib/python3.7/site-packages/github3/structs.py:11: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  class GitHubIterator(models.GitHubCore, collections.Iterator):

In [2]: yamls = parse_meta_yaml_to_outputs_dicts("linux", "64", "../ctng-compilers-feedstock/recipe", "../ctng-compilers-feedstock/.ci_support/linux_64_ctng_binutils2.29.
   ...: 1ctng_cpu_archaarch64ctng_gcc9.3.0ctng_target_platformlinux-aarch64old_ctng_vendorconda_cos7target_platformlinux-64.yaml")                                        
/Users/beckermr/miniconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/_vendor/five.py:49: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload                  # noqa
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
Adding in variants from ../ctng-compilers-feedstock/recipe/conda_build_config.yaml
Adding in variants from ../ctng-compilers-feedstock/.ci_support/linux_64_ctng_binutils2.29.1ctng_cpu_archaarch64ctng_gcc9.3.0ctng_target_platformlinux-aarch64old_ctng_vendorconda_cos7target_platformlinux-64.yaml
Adding in variants from /Users/beckermr/Desktop/ctng-compilers-feedstock/recipe/conda_build_config.yaml
Adding in variants from argument_variants
Attempting to finalize metadata for binutils_impl_linux-aarch64
Attempting to finalize metadata for libgcc-devel_linux-aarch64
Attempting to finalize metadata for libstdcxx-devel_linux-aarch64
Attempting to finalize metadata for gcc_impl_linux-aarch64
Attempting to finalize metadata for gfortran_impl_linux-aarch64
Attempting to finalize metadata for gxx_impl_linux-aarch64

In [3]: yamls                                                                                                                                                             
Out[3]: 
[{'package': {'name': 'binutils_impl_linux-aarch64', 'version': '2.29.1'},
  'source': {'path': '.'},
  'build': {'number': 15,
   'detect_binary_files_with_prefix': False,
   'binary_relocation': ['bin/*', 'lib/*.so', 'libexec/**/*.so*'],
   'missing_dso_whitelist': ['*']},
  'requirements': {'run': ['sysroot_linux-aarch64'],
   'run_constrained': ['gcc_impl_linux-aarch64 9.3.0.*',
    'gfortran_impl_linux-aarch64 9.3.0.*']},
  'extra': {'recipe-maintainers': ['isuruf', 'beckermr'],
   'final': True,
   'parent_recipe': {'path': '/Users/beckermr/Desktop/ctng-compilers-feedstock/recipe',
    'name': 'ctng-compilers',
    'version': '9.3.0'}},
  'test': {'commands': ['test -f ${PREFIX}/aarch64-conda-linux-gnu/bin/ar',
    'test -f ${PREFIX}/aarch64-conda-linux-gnu/bin/ld',
    'test -f ${PREFIX}/bin/aarch64-conda_cos7-linux-gnu-ar',
    'test -f ${PREFIX}/bin/aarch64-conda-linux-gnu-ar',
    'test -f ${PREFIX}/bin/aarch64-conda_cos7-linux-gnu-ld',
    'test -f ${PREFIX}/bin/aarch64-conda-linux-gnu-ld']},
  'about': {'summary': 'The GNU Binutils are a collection of binary tools.',
   'home': 'https://www.gnu.org/software/binutils/',
   'license': 'GPL-3.0-or-later'}},
 {'package': {'name': 'libgcc-devel_linux-aarch64', 'version': '9.3.0'},
  'source': {'path': '.'},
  'build': {'number': 15,
   'detect_binary_files_with_prefix': False,
   'binary_relocation': False,
   'missing_dso_whitelist': ['*']},
  'requirements': {},
  'extra': {'recipe-maintainers': ['isuruf', 'beckermr'],
   'final': True,
   'parent_recipe': {'path': '/Users/beckermr/Desktop/ctng-compilers-feedstock/recipe',
    'name': 'ctng-compilers',
    'version': '9.3.0'}},
  'test': {'commands': ['test -f ${PREFIX}/lib/gcc/aarch64-conda-linux-gnu/9.3.0/crtbegin.o']},
  'about': {'summary': 'The GNU C development libraries and object files',
   'home': 'https://gcc.gnu.org/',
   'license': 'GPL-3.0-with-GCC-exception'}},
 {'package': {'name': 'libstdcxx-devel_linux-aarch64', 'version': '9.3.0'},
  'source': {'path': '.'},
  'build': {'number': 15,
   'detect_binary_files_with_prefix': False,
   'binary_relocation': False,
   'missing_dso_whitelist': ['*']},
  'requirements': {},
  'extra': {'recipe-maintainers': ['isuruf', 'beckermr'],
   'final': True,
   'parent_recipe': {'path': '/Users/beckermr/Desktop/ctng-compilers-feedstock/recipe',
    'name': 'ctng-compilers',
    'version': '9.3.0'}},
  'test': {'commands': ['test -f ${PREFIX}/aarch64-conda-linux-gnu/lib/libstdc++.a']},
  'about': {'summary': 'The GNU C++ headers and development libraries',
   'home': 'https://gcc.gnu.org/',
   'license': 'GPL-3.0-with-GCC-exception'}},
 {'package': {'name': 'gcc_impl_linux-aarch64', 'version': '9.3.0'},
  'source': {'path': '.'},
  'build': {'number': 15,
   'detect_binary_files_with_prefix': False,
   'binary_relocation': ['bin/*',
    'lib/*.so*',
    'libexec/**/*.so*',
    'libexec/**/cc1*',
    'libexec/**/collect2',
    'libexec/**/gcc',
    'libexec/**/lto*',
    'libexec/**/plugin/gengtype'],
   'missing_dso_whitelist': ['*'],
   'runpath_whitelist': ['x86_64-conda-linux-gnu/sysroot/lib/libpthread-2.12.2.so'],
   'ignore_run_exports': ['__glibc']},
  'requirements': {'host': ['sysroot_linux-aarch64 2.17'],
   'run': ['binutils_impl_linux-aarch64 >=2.29.1',
    'libgcc-devel_linux-aarch64 9.3.0 15',
    'sysroot_linux-aarch64',
    'libstdcxx-ng >=4.9',
    'libgcc-ng >=4.9']},
  'extra': {'recipe-maintainers': ['isuruf', 'beckermr'],
   'final': True,
   'parent_recipe': {'path': '/Users/beckermr/Desktop/ctng-compilers-feedstock/recipe',
    'name': 'ctng-compilers',
    'version': '9.3.0'}},
  'test': {'requires': ['sysroot_linux-aarch64 2.17'],
   'files': ['tests'],
   'commands': ['echo aarch64-unknown-linux-gnu',
    'echo 2.17',
    'echo conda_cos7',
    'echo 3.10',
    'test -f ${PREFIX}/bin/aarch64-conda_cos7-linux-gnu-gcc',
    'CC=$(${PREFIX}/bin/*-gcc -dumpmachine)-gcc',
    '${CC} -Wall tests/aligned_alloc.c -c -o c_aligned.o -v']},
  'about': {'summary': 'GNU C Compiler',
   'home': 'https://gcc.gnu.org/',
   'license': 'GPL-3.0-with-GCC-exception'}},
 {'package': {'name': 'gfortran_impl_linux-aarch64', 'version': '9.3.0'},
  'source': {'path': '.'},
  'build': {'number': 15,
   'detect_binary_files_with_prefix': False,
   'binary_relocation': ['bin/*',
    'lib/*.so',
    'libexec/**/*.so*',
    'libexec/**/f951'],
   'missing_dso_whitelist': ['*'],
   'ignore_run_exports': ['__glibc']},
  'requirements': {'build': ['gcc_impl_linux-aarch64 9.3.0 15'],
   'host': ['gcc_impl_linux-aarch64 9.3.0 15', 'sysroot_linux-aarch64'],
   'run': ['gcc_impl_linux-aarch64 >=9.3.0',
    'sysroot_linux-aarch64',
    'libgcc-ng >=4.9',
    'libstdcxx-ng >=4.9']},
  'extra': {'recipe-maintainers': ['isuruf', 'beckermr'],
   'final': True,
   'parent_recipe': {'path': '/Users/beckermr/Desktop/ctng-compilers-feedstock/recipe',
    'name': 'ctng-compilers',
    'version': '9.3.0'}},
  'test': {'requires': ['cmake >=3.11', 'sysroot_linux-aarch64 2.17'],
   'commands': ['test -f ${PREFIX}/bin/aarch64-conda_cos7-linux-gnu-gfortran',
    'test -f ${PREFIX}/bin/aarch64-conda-linux-gnu-gfortran',
    "find $PREFIX/lib -iname omp_lib.mod | grep '.'",
    "find $PREFIX/lib -iname omp_lib.h | grep '.'",
    'pushd tests/fortomp'],
   'files': ['tests/fortomp/*']},
  'about': {'summary': 'GNU Fortran Compiler',
   'home': 'https://gcc.gnu.org/',
   'license': 'GPL-3.0-with-GCC-exception'}},
 {'package': {'name': 'gxx_impl_linux-aarch64', 'version': '9.3.0'},
  'source': {'path': '.'},
  'build': {'number': 15,
   'detect_binary_files_with_prefix': False,
   'binary_relocation': ['bin/*',
    'lib/*.so',
    'libexec/**/*.so*',
    'libexec/**/cc1*'],
   'missing_dso_whitelist': ['*'],
   'ignore_run_exports': ['__glibc']},
  'requirements': {'host': ['gcc_impl_linux-aarch64 9.3.0 15'],
   'run': ['gcc_impl_linux-aarch64 9.3.0 15',
    'sysroot_linux-aarch64',
    'libstdcxx-devel_linux-aarch64 9.3.0 15']},
  'extra': {'recipe-maintainers': ['isuruf', 'beckermr'],
   'final': True,
   'parent_recipe': {'path': '/Users/beckermr/Desktop/ctng-compilers-feedstock/recipe',
    'name': 'ctng-compilers',
    'version': '9.3.0'}},
  'test': {'requires': ['sysroot_linux-aarch64 2.17'],
   'files': ['tests'],
   'commands': ['test -f ${PREFIX}/bin/aarch64-conda_cos7-linux-gnu-g++',
    'test -f ${PREFIX}/bin/aarch64-conda-linux-gnu-g++',
    'CXX=$(${PREFIX}/bin/*-gcc -dumpmachine)-g++',
    '${CXX} -Wall tests/aligned_alloc.cpp -c -o cpp_aligned.o --std=c++17']},
  'about': {'summary': 'GNU C++ Compiler',
   'home': 'https://gcc.gnu.org/',
   'license': 'GPL-3.0-with-GCC-exception'}}]
```

**Comment by CJ-Wright** [comment]
What is the best way to extract the variant associated with each result? For instance the osx migrator would prefer requirements from an osx varient if possible.

**Comment by beckermr** [comment]
You feed in the platform and arch, so you know what platform you are on in the first place. Plus you have to feed in the c support conda_build_config so you can pull any keys from there too.

**Comment by CJ-Wright** [comment]
ok

**Pull request closed without merging**
