### PR TITLE
Support `disabled` bot inspection

### PR DESCRIPTION
**Pull request by ytausch**
see #2272

### CODE REVIEW

**Comment by ytausch** [comment]
@beckermr You mentioned something about changing user instructions that say something about `bot.inspection = False` but I could not find them.

**Comment by beckermr** [comment]
Yep here: https://github.com/ytausch/cf-scripts/blob/disabled-inspection/conda_forge_tick/update_deps.py#L433

**Comment by ytausch** [comment]
I just found out that the relevant code is (very unfortunately) duplicated here:
https://github.com/regro/cf-scripts/blob/ac2187a6a4166ddc23380686812dc43ed2e01d5d/conda_forge_tick/migrators/dep_updates.py#L33-L56

This code duplication should be removed - and also here, `get_dep_updates_and_hints` can be called with `False` or `disabled` which is incorrect.

**Review by beckermr — APPROVED** [review]
Thank you!

**Pull request merged**
