### PR TITLE
DOC improved PR message

### LINKED ISSUE #104: Comment and question
I *love* the idea of the auto update but conda forge requires humans to maintain and check PRs. 

Maybe the message in the PRs could be clearer by explaining what this repo does and what the expectations are for how it’s PRs should be handled?

### PR DESCRIPTION
**Pull request by beckermr**
This PR has an improved (?) PR message. 

Closes #104 

@CJ-Wright for viz

### CODE REVIEW

**Comment by beckermr** [comment]
@dougalsutherland You will have to merge the PR as I do not have write access. Thanks for reviewing!

**Comment by dougalsutherland** [comment]
I don't either, I was just signaling my approval. :)

**Comment by CJ-Wright** [comment]
@beckermr Thank you very much for putting this in!

**Comment by jakirkham** [comment]
Thanks @beckermr. This is a very nice improvement. :)

**Pull request merged**
