### PR TITLE
Switch to get_cran_index from conda-build

### PR DESCRIPTION
**Pull request by dbast**
The included code previously was on conda-build master branch only and now can be used via the released conda-build version 3.18.10.

That means less code to maintain on cf-scripts side :)

### CODE REVIEW

**Comment by dbast** [comment]
This has to wait, because of https://github.com/conda-forge/conda-build-feedstock/issues/118

**Comment by dbast** [comment]
I guess this can be merged now... conda 3.18.10 was not marked as broken and also the new conda 3.18.11 is available and contains the required `conda_build.skeletons.cran.get_cran_index` functions.

**Comment by CJ-Wright** [comment]
I think this looks reasonable, but I can't baby sit the bot.

**Comment by beckermr** [comment]
I just had a lot If trouble with this section of the bot and performance issues. Agreed the bot needs baby sitting for this change.

**Comment by scopatz** [comment]
There are conflicts for this now

**Pull request closed without merging**
