### PR TITLE
REF run the piggyback migrations first

### PR DESCRIPTION
**Pull request by beckermr**
This PR runs the piggyback migrations first. It will help us address #847 and #791.

### CODE REVIEW

**Comment by djhoese** [comment]
Small question: why the `swap_piggyback` in the tests?

**Comment by beckermr** [comment]
I am removing this but the github api is being flaky

**Comment by beckermr** [comment]
there is a commit already pushed where I split into pre and post migrators - it turns out the license minimigrator relies on the source of the package and so it has to be run after the version is updated. I did swap the default to run the minimigrators before the main one

**Comment by beckermr** [comment]
there is a commit already pushed where I split into pre and post migrators - it turns out the license minimigrator relies on the source of the package and so it has to be run after the version is updated. I did swap the default to run the minimigrators before the main one

**Comment by scopatz** [comment]
This LGTM!

**Comment by beckermr** [comment]
It is not showing my latest commit.

**Pull request merged**
