### PR TITLE
better PR title and body for close outs

### PR DESCRIPTION
**Pull request by CJ-Wright**
CC @beckermr

### CODE REVIEW

**Comment by CJ-Wright** [comment]
btw this got opened https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/514

**Comment by beckermr** [comment]
Was root base done ~12 hours ago? IDK

**Comment by CJ-Wright** [comment]
root base has been done for a while

**Comment by beckermr** [comment]
Merge?

**Pull request merged**
