### PR TITLE
Add piggyback migrator for flang

### PR DESCRIPTION
**Pull request by h-vetinari**
This one was harder than usual because of some fun Python regex bugs and the "take all consecutive compilers in a block" logic. 🙃 

I'll note that the target here (as for most piggyback migrators) is not 100% perfection, but to reliably switch over to flang. It's better that a bot PR fails spuriously and we fix it manually, rather than that it is rerendered incorrectly (i.e. not activating flang) and merged prematurely simply because CI is green.

Here the diffs for the before/after in the tests for ease of review (minus the spurious version bumps from abusing the version migrator as a crutch), generated with
```
git diff HEAD:tests/test_yaml/flang_<pkg>_before_meta.yaml..HEAD:tests/test_yaml/flang_<pkg>_after_meta.yaml
```

<details>
<summary>lapack</summary>

```diff
diff --git a/tests/test_yaml/flang_lapack_before_meta.yaml b/tests/test_yaml/flang_lapack_after_meta.yaml
index 6c3f45cf..1189ba3d 100644
--- a/tests/test_yaml/flang_lapack_before_meta.yaml
+++ b/tests/test_yaml/flang_lapack_after_meta.yaml
@@ -33,14 +33,9 @@ build:
 
 requirements:
   build:
-    - {{ compiler("c") }}               # [unix]
-    - {{ stdlib("c") }}                 # [unix]
-    - {{ compiler("fortran") }}         # [unix]
-    - {{ compiler("m2w64_c") }}         # [win]
-    - {{ stdlib("m2w64_c") }}           # [win]
-    - {{ compiler("m2w64_fortran") }}   # [win]
-    # This is just for creating the import libaries
-    - vs2019_win-64                     # [win64]
+    - {{ stdlib("c") }}
+    - {{ compiler("c") }}
+    - {{ compiler("fortran") }}
     - ninja                             # [win]
     - make                              # [unix]
     - cmake
@@ -58,12 +53,9 @@ outputs:
         - {{ pin_subpackage("libblas", max_pin="x") }}
     requirements:
       build:
-        - {{ compiler("c") }}               # [unix]
-        - {{ stdlib("c") }}                 # [unix]
-        - {{ compiler("fortran") }}         # [unix]
-        - {{ compiler("m2w64_c") }}         # [win]
-        - {{ stdlib("m2w64_c") }}           # [win]
-        - {{ compiler("m2w64_fortran") }}   # [win]
+        - {{ stdlib("c") }}
+        - {{ compiler("c") }}
+        - {{ compiler("fortran") }}
       run_constrained:
         - blas * netlib
     files:
@@ -91,12 +83,9 @@ outputs:
         - {{ pin_subpackage("libtmglib", max_pin="x") }}
     requirements:
       build:
-        - {{ compiler("c") }}               # [unix]
-        - {{ stdlib("c") }}                 # [unix]
-        - {{ compiler("fortran") }}         # [unix]
-        - {{ compiler("m2w64_c") }}         # [win]
-        - {{ stdlib("m2w64_c") }}           # [win]
-        - {{ compiler("m2w64_fortran") }}   # [win]
+        - {{ stdlib("c") }}
+        - {{ compiler("c") }}
+        - {{ compiler("fortran") }}
       run_constrained:
         - blas * netlib
     files:
@@ -122,12 +111,9 @@ outputs:
         - {{ pin_subpackage("libcblas", max_pin="x") }}
     requirements:
       build:
-        - {{ compiler("c") }}               # [unix]
-        - {{ stdlib("c") }}                 # [unix]
-        - {{ compiler("fortran") }}         # [unix]
-        - {{ compiler("m2w64_c") }}         # [win]
-        - {{ stdlib("m2w64_c") }}           # [win]
-        - {{ compiler("m2w64_fortran") }}   # [win]
+        - {{ stdlib("c") }}
+        - {{ compiler("c") }}
+        - {{ compiler("fortran") }}
       run:
         - libblas {{ version }}
     files:
@@ -157,12 +143,9 @@ outputs:
         - {{ pin_subpackage("liblapack", max_pin="x") }}
     requirements:
       build:
-        - {{ compiler("c") }}               # [unix]
-        - {{ stdlib("c") }}                 # [unix]
-        - {{ compiler("fortran") }}         # [unix]
-        - {{ compiler("m2w64_c") }}         # [win]
-        - {{ stdlib("m2w64_c") }}           # [win]
-        - {{ compiler("m2w64_fortran") }}   # [win]
+        - {{ stdlib("c") }}
+        - {{ compiler("c") }}
+        - {{ compiler("fortran") }}
       run:
         - libblas {{ version }}
     files:
@@ -191,12 +174,9 @@ outputs:
         - {{ pin_subpackage("liblapacke", max_pin="x") }}
     requirements:
       build:
-        - {{ compiler("c") }}               # [unix]
-        - {{ stdlib("c") }}                 # [unix]
-        - {{ compiler("fortran") }}         # [unix]
-        - {{ compiler("m2w64_c") }}         # [win]
-        - {{ stdlib("m2w64_c") }}           # [win]
-        - {{ compiler("m2w64_fortran") }}   # [win]
+        - {{ stdlib("c") }}
+        - {{ compiler("c") }}
+        - {{ compiler("fortran") }}
       run:
         - libblas    {{ version }}
         - libcblas   {{ version }}
```

</details>

<details>
<summary>prima</summary>

```diff
diff --git a/tests/test_yaml/flang_prima_before_meta.yaml b/tests/test_yaml/flang_prima_after_meta.yaml
index 26c0b13e..33c42fe9 100644
--- a/tests/test_yaml/flang_prima_before_meta.yaml
+++ b/tests/test_yaml/flang_prima_after_meta.yaml
@@ -22,15 +22,10 @@ requirements:
   build:
     - cmake
     - ninja
-    - {{ compiler("c") }}               # [unix]
-    - {{ stdlib("c") }}                 # [unix]
-    - {{ compiler("fortran") }}         # [unix]
-    # flang does not support F2018, use gfortran
-    - {{ compiler("m2w64_c") }}         # [win]
-    - {{ stdlib("m2w64_c") }}           # [win]
-    - {{ compiler("m2w64_fortran") }}   # [win]
+    - {{ stdlib("c") }}
+    - {{ compiler("c") }}
+    - {{ compiler("fortran") }}
   run:
-    - m2w64-gcc-libgfortran  # [win]
 
 test:
   commands:
```

</details>

</details>

<details>
<summary>mfront</summary>

```diff
diff --git a/tests/test_yaml/flang_mfront_before_meta.yaml b/tests/test_yaml/flang_mfront_after_meta.yaml
index 398792f4..c0f4d1b6 100644
--- a/tests/test_yaml/flang_mfront_before_meta.yaml
+++ b/tests/test_yaml/flang_mfront_after_meta.yaml
@@ -25,14 +25,13 @@ build:
 
 requirements:
   build:
-    - {{ compiler('fortran') }}  # [not win]
+    - {{ compiler("fortran") }}
     - {{ compiler('c') }}
     - {{ stdlib("c") }}
     - {{ compiler('cxx') }}
     - cmake
     - make  # [not win]
     - ninja                       # [win]
-    - flang                       # [win]
     - clang                       # [win]
     - lld                         # [win]
     - libgomp  # [linux]
```

</details>

</details>

<details>
<summary>plplot</summary>

```diff
diff --git a/tests/test_yaml/flang_plplot_before_meta.yaml b/tests/test_yaml/flang_plplot_after_meta.yaml
index e3bcd4a0..2201afb1 100644
--- a/tests/test_yaml/flang_plplot_before_meta.yaml
+++ b/tests/test_yaml/flang_plplot_after_meta.yaml
@@ -21,11 +21,10 @@ build:
 
 requirements:
   build:
-    - {{ compiler('c') }}
     - {{ stdlib("c") }}
-    - {{ compiler('cxx') }}
-    - {{ compiler('fortran') }}  # [unix]
-    - {{ compiler('m2w64_fortran') }}  # [win]
+    - {{ compiler("c") }}
+    - {{ compiler("cxx") }}
+    - {{ compiler("fortran") }}
     - clang  # [win]
     - cmake
     - ninja
```

</details>

</details>

<details>
<summary>pcmsolver-split</summary>

```diff
diff --git a/tests/test_yaml/flang_pcmsolver-split_before_meta.yaml b/tests/test_yaml/flang_pcmsolver-split_after_meta.yaml
index 7e6898bb..02503f40 100644
--- a/tests/test_yaml/flang_pcmsolver-split_before_meta.yaml
+++ b/tests/test_yaml/flang_pcmsolver-split_after_meta.yaml
@@ -25,13 +25,10 @@ requirements:
   build:
     - python                              # [build_platform != target_platform]
     - cross-python_{{ target_platform }}  # [build_platform != target_platform]
-    - {{ compiler('c') }}                 # [unix]
-    - {{ stdlib("c") }}                   # [unix]
-    - {{ compiler('cxx') }}               # [unix]
-    - {{ compiler('fortran') }}           # [unix]
-    - {{ compiler('m2w64_c') }}           # [win]
-    - {{ stdlib("c") }}                   # [win]
-    - {{ compiler('m2w64_fortran') }}     # [win]
+    - {{ stdlib("c") }}
+    - {{ compiler("c") }}
+    - {{ compiler("cxx") }}
+    - {{ compiler("fortran") }}
     - cmake
     - make                                # [unix]
     - ninja                               # [win]
@@ -41,7 +38,6 @@ requirements:
     - python
     - zlib
   run:
-    - m2w64-gcc-libgfortran               # [win]
     - python
 
 outputs:
@@ -107,19 +103,15 @@ outputs:
         - {{ pin_subpackage('libpcm', max_pin='x.x.x') }}
     requirements:
       build:
-        - {{ compiler('c') }}              # [unix]
-        - {{ stdlib("c") }}                # [unix]
-        - {{ compiler('cxx') }}            # [unix]
-        - {{ compiler('fortran') }}        # [unix]
-        - {{ compiler('m2w64_c') }}        # [win]
-        - {{ stdlib("c") }}                # [win]
-        - {{ compiler('m2w64_fortran') }}  # [win]
+        - {{ stdlib("c") }}
+        - {{ compiler("c") }}
+        - {{ compiler("cxx") }}
+        - {{ compiler("fortran") }}
       host:
         - libboost-headers
         - eigen
         - zlib
       run:
-        - m2w64-gcc-libgfortran            # [win]
     files:
       - bin/run_pcm                        # [unix]
       - lib/libpcm*                        # [unix]
```

</details>

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
The code here is quite impressive!

Why do all compiler lines have to be in a single block?

I would have thought it would be simpler to take passes through the lines as follows:

1. On the first pass, convert any `m2w64_` compiler statement to the one without the prefix.
2. On the second pass, find all compiler or stdlib lines that are the same but with different selectors.
3. On the third pass, remove the duplicated statements from 2 by writing a single statement without selectors and removing the other line.

**Comment by h-vetinari** [comment]
> Why do all compiler lines have to be in a single block?

They don't it just so happens that the vast majority of recipes are organised this way. The idea is to proactively switch away from the `m2w64_` compilers on windows (if we find `m2w64_fortran`) and then ensure a unified compiler section without duplication or selectors.

> I would have thought it would be simpler to take passes through the lines as follows: [...]

I don't consider this much simpler TBH, and it would IMO yield a lower-quality conversion.

**Comment by h-vetinari** [comment]
> Why do all compiler lines have to be in a single block?

Another clarification perhaps: they don't have to be a single block for the migrator to work. Rather, the piggyback migrator will simply consider all the compiler-ish lines surrounding `{{ compiler("m2w64_fortran") }}` and use that to determine which compilers should be replaced.

In particular, the logic will continue to work if someone has their compilers interspersed with other dependencies. In that case, it'll just mean that the compiler section will not be homogenized by the migrator, but we'll only end up doing something like
```diff
@@ -22,15 +22,10 @@ requirements:
   build:
     - cmake
     - ninja
     - {{ stdlib("c") }}                 # [unix]
     - {{ compiler("c") }}               # [unix]
     - {{ compiler("fortran") }}         # [unix]
     - foo  # due to interspersed non-compiler deps, the compilers above...
     - bar  # ... will not be detected as belonging to the m2w64_fortran "block" 
-    - {{ compiler("m2w64_c") }}         # [win]
-    - {{ stdlib("m2w64_c") }}           # [win]
-    - {{ compiler("m2w64_fortran") }}   # [win]
+    - {{ stdlib("c") }}
+    - {{ compiler("c") }}
+    - {{ compiler("fortran") }}
     - baz
     - quux

**Comment by beckermr** [comment]
The algorithm I suggested would AFAIK correctly migrate all of the tests you added and would migrate the example in your last comment without leaving duplicate compiler lines. I don't think it would yield lower quality migrations at all.

**Comment by h-vetinari** [comment]
> @beckermr: The algorithm I suggested would AFAIK correctly migrate all of the tests you added and would migrate the example in your last comment without leaving duplicate compiler lines. I don't think it would yield lower quality migrations at all.

I consider this a working (and demonstrably tested) implementation - even if your proposal can be made to work, what are the benefits of reimplementing this in a different way? Is there any particular point that you're objecting to in the implementation? I don't think changing this is a worthwhile time investment - this is a one-shot piggyback, so in a few weeks the implementation will be only of historical interest. Also I'll be keeping a close eye on the migration anyway. C.f. also from the OP

> @h-vetinari: I'll note that the target here (as for most piggyback migrators) is not 100% perfection, but to reliably switch over to flang. It's better that a bot PR fails spuriously and we fix it manually, rather than that it is rerendered incorrectly (i.e. not activating flang) and merged prematurely simply because CI is green.

**Review by beckermr — APPROVED** [review]
The intent of my comment is to make the migrator more robust and produce better outcomes. This is not a sticking point for me though, so LGTM.

**Comment by h-vetinari** [comment]
> The intent of my comment is to make the migrator more robust and produce better outcomes.

Understood. Let's give this a shot as-is, as I said I'll be closely monitoring the PRs anyway. If something turns out to be problematic, I'm happy to fix it, or even switch implementations.

**Pull request merged**
