### PR TITLE
Add R UCRT cleanup mini migrator

### PR DESCRIPTION
**Pull request by isuruf**
- [ ] Pydantic model updated or no update needed

### CODE REVIEW

**Review by beckermr — COMMENTED** [review]
This PR could definitely use a test.

**Comment by beckermr** [comment]
pre-commit.ci autofix

**Review by beckermr — APPROVED** [review]
LGTM! Once you are happy with the PR, merge away!

**Comment by isuruf** [comment]
@bgruening @mfansler, we need to add these changes to conda_r_skeleton_helper too.

**Comment by mbargull** [comment]
There appear to be recipes that have the `m2w64-` packages added verbatim and not via `{{ native }}`:
https://github.com/conda-forge/r-stringi-feedstock/blob/89e399212d8ac729721523b1415c071d2c16b641/recipe/meta.yaml#L48
https://github.com/regro/cf-scripts/actions/runs/9729117591

But: Those are very few: https://github.com/search?q=org%3Aconda-forge+path%3Arecipe%2Fmeta.yaml+%2F-+m2w64-%2F+%2F-+r-base%2F&type=code
=> we can handle them manually

**Pull request merged**
