### PR TITLE
escape commit message properly, fixes errors associated with 'Rebuild for python38'

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by beckermr** [comment]
Can you explain what this fixes?

**Comment by CJ-Wright** [comment]
`subprocess.CalledProcessError: Command '['git', 'commit', '-am', 'Rebuild for python38']' returned non-zero exit status 1.`
in 
https://app.circleci.com/pipelines/github/regro/circle_worker/5114/workflows/7a52da47-e2e0-4222-9cc4-efaa21cbc65e/jobs/20539

**Comment by beckermr** [comment]
Hmm ok. This was working before I thought but sure.

**Comment by beckermr** [comment]
I don't think the error is from this.

It quotes properly already.

```
In [3]: subprocess.run(["git", "commit", "--allow-empty", "-am", "a msg yes"], check=True)                                                                                
[master 7ca4a42] a msg yes
Out[3]: CompletedProcess(args=['git', 'commit', '--allow-empty', '-am', 'a msg yes'], returncode=0)
```

**Pull request closed without merging**
