### PR TITLE
Changes to auto_tick profiler.

### PR DESCRIPTION
**Pull request by viniciusdc**
I've opted for `prof` instead of `profile_profiler`, removed the `print_stats` statements (and correlated). I will try  to use `dump_stats`  to enable further visualization of the information (if needed), and as the last update I've put a script/function name at the profile name to facilitate the inspection  and search for the any necessary files (principally when we have multiple profiler running).

### CODE REVIEW

**Comment by beckermr** [comment]
Tests need to pass before this can be merged.

**Comment by viniciusdc** [comment]
> Tests need to pass before this can be merged.

Right, but IDK what happened with Travis (by the logs it seems to be an error with the Migrator)

**Comment by viniciusdc** [comment]
This PR will wait until #1111 works and after that we should merge #1110 to enhance this PR with the new `@profiling` decorator.

**Comment by beckermr** [comment]
closing as no longer needed I think

**Pull request closed without merging**
