### PR TITLE
apply fixes

### PR DESCRIPTION
**Pull request by ocefpaf**
@CJ-Wright and @beckermr this causes a lot of code churn but it will make reviewing new PRs easier. Close it or merge, I don't have a strong opinion on it and it is easy enough to re-do this with `pre-commit run --all-files`.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Note that the only check failing is `check-yaml`: https://github.com/regro/cf-scripts/pull/1042/checks?check_run_id=785331795

I'm not sure those are useful.

**Comment by beckermr** [comment]
Also I noticed one of the comma things messign with json files...

**Comment by beckermr** [comment]
Any more changes here @ocefpaf?

**Comment by ocefpaf** [comment]
> Any more changes here @ocefpaf?

Nope. Good to go if you think these changes are OK.

**Pull request merged**
