### PR TITLE
stop bot

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by justcalamari** [comment]
Why are we stopping the bot?

**Comment by CJ-Wright** [comment]
@isuruf wanted to run some token magic and was worried about the bot's PR impacting the API limit.

**Comment by CJ-Wright** [comment]
The plan is for someone to merge the PR, do all the token stuff, then revert the merge when it is all done.

**Comment by CJ-Wright** [comment]
The bot is currently finishing up a run, so it should be done in the next 30 mins or so.

**Pull request merged**
