### PR TITLE
Pypi dev rel

### LINKED ISSUE #119: PYPI inherits from main class
Currently PYPI is a stand alone, so it doesn't inherit the blacklist. It should inherit the blacklist.

### PR DESCRIPTION
**Pull request by CJ-Wright**
Closes #119

### CODE REVIEW

**Comment by CJ-Wright** [comment]
I think the cran change is ok. From what I can see from https://cran.r-project.org/src/contrib/ all the versions have - rather than _

**Comment by isuruf** [comment]
But the conda package versions have `_` instead of `-`

**Comment by scopatz** [comment]
That is true.  I think consistency is important here. The question is just what are we going to be consistent with. This is an easy thing to switch back if needed.

**Comment by scopatz** [comment]
ie conda or cran. it probably matters what we are comparing against

**Comment by isuruf** [comment]
This change will indicate that `1.1-3` is not equal to `1.1_3` (conda version) and will indicate that a version bump is needed. Please revert the last commit.

**Comment by CJ-Wright** [comment]
Reversion is here: https://github.com/regro/cf-scripts/pull/121
Will merge at 5:30 EST if no objections. (The bot runs every 6 hours (starting midnight EST))

**Pull request merged**
