### PR TITLE
better pin filter

### LINKED ISSUE #289: Make pinning removal a bit more precise
Would it be possible to have the pinning filter remove things which aren't pinned? Otherwise we're going to run on a lot of things.
Attn: @justcalamari

### PR DESCRIPTION
**Pull request by CJ-Wright**
Closes #289

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@justcalamari

**Comment by justcalamari** [comment]
My problem with this is that now filter is doing the same stuff that migrate is doing, so for any feedstock with pinnings, we would be running the same code twice. It might be better to just check in migrate if there is a pinning and if not return False.

**Comment by justcalamari** [comment]
Also we should probably bump the build number in migrate.

**Comment by CJ-Wright** [comment]
@justcalamari I think this is ready for another round.

**Comment by justcalamari** [comment]
Thanks, @CJ-Wright!

**Comment by CJ-Wright** [comment]
Thank you!

**Pull request merged**
