### PR TITLE
WIP: init docs

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
Looks good.  Do you plan on doing the doctr thing to build these later?

**Comment by CJ-Wright** [comment]
Yes, I think doctr would be great! Note that this needs some updates based on #459

**Comment by scopatz** [comment]
LGTM. Any reason not to merge?

**Comment by CJ-Wright** [comment]
Yes, I need to update the making a migrator, since we can now create a new migrator at the object level rather than class level.

**Comment by CJ-Wright** [comment]
Now this should be ready.

**Pull request merged**
