### PR TITLE
ping maintainers if PR is ready for review

### PR DESCRIPTION
**Pull request by CJ-Wright**
I think this is ready for review @mariusvniekerk @scopatz

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@regro/auto-tick ready for reivew (this way I get everybody!)

**Comment by mariusvniekerk** [comment]
Do we do something to avoid pinging repeatedly?

**Comment by CJ-Wright** [comment]
We check if the last message is ours. If someone comments on the PR/updates the PR it will (should?) trigger another ping. I thought this would be helpful since if you update a PR you might have to wait a while to do something so it may be helpful to have multiple pings.

**Comment by isuruf** [comment]
Can you explain what this does? Does this look at all the PRs of all feedstocks?

**Comment by mariusvniekerk** [comment]
Okay.  I can see both the use and potential annoyance.  LGTM

**Comment by isuruf** [comment]
Shouldn't this be in conda-forge-webservices?

**Comment by CJ-Wright** [comment]
@isuruf This would (for the bot's PRs) ping the maintainers when all the statuses are no longer pending so they can evaluate the changes and fix/close/merge the PR. Note that we don't ping the maintainers if the last comment is ours (so we don't re-ping every time the bot runs).

**Comment by CJ-Wright** [comment]
I would love to have this in the webservices but I think this is a workable stopgap and is especially important if we want to run though the compiler migration at a quick pace (since we are depending on maintainers to merge things in a timely manner). I don't really understand what changes would need to go into the webservices to have this kind of functionality.

**Comment by CJ-Wright** [comment]
@mariusvniekerk I could put a tighter leash on this and check if the last comment is ours and that the status hasn't changed since our last comment. This would prevent people from being pinged during a PR discussion.

**Comment by isuruf** [comment]
With conda-forge-webservices, you just listen to the PR status event of a PR and do whatever you do here.

Btw, it's better to request a review than to ping. You can easily list PRs with review requests.

**Comment by CJ-Wright** [comment]
I will update this to be a review request.

**Comment by scopatz** [comment]
Looks like there are some conflicts

**Comment by CJ-Wright** [comment]
Yea, I also need to change it over to a review request and check that the status hasn't changed before ping.

**Comment by CJ-Wright** [comment]
Just as a followup, we went with a comment, because only people with write permissions can ask for review.

**Pull request closed without merging**
