### PR TITLE
TST add mpich test case

### PR DESCRIPTION
**Pull request by beckermr**
closes https://github.com/regro/cf-scripts/issues/1784

### CODE REVIEW

**Comment by beckermr** [comment]
@jakirkham @dalcinl IDK if I gave bad advice before or not. If I did, my apologies. The syntax

```
{% set version_url = version if version[-2:] != ".0" else version[:-2] %}
```

appears to work. I think the fix is to use an inline if statement.

I added tests to the bot to make sure it continues to work.

If the logic appears sound, then let's make the change in the mpich feedstock and merge this PR.

If this is what mpich had before the last change, then we'll need ot dig more.

**Comment by dalcinl** [comment]
> If I did, my apologies.

Oh, no, it was not you, and it is not a big deal anyway, corner cases happen all the time.

> If the logic appears sound,

It does. I'll submit a fix PR in the mpich feedstock and ping you.

**Comment by beckermr** [comment]
On the logic, you may need to handle the case of "5.0" vs "5.0.0". I think the current snippet would strip "5.0" down to "5".

**Comment by dalcinl** [comment]
@beckermr Maybe we are not in the same page. Let me try to explain myself better. If nothing change, at some point MPICH will release the next minor release `4.2`, and the version number in the MPICH side will be `4.2` WITHOUT a trailing `.0` as SemVer would require. However, in the recipe, I want the version to follow SemVer, that is, I want the recipe version to say `version = "4.2.0"`.  Therefore, I must to use the `version_url=4.2` hack to be able to download the release tarball. But will the bot actually figure out that there is a new release? I'm not sure how all this works.

**Comment by beckermr** [comment]
ohhhh nvm you are correct!

**Pull request merged**
