### PR TITLE
BUG make sure to handle tuples

### PR DESCRIPTION
**Pull request by beckermr**
This fixes some issues w/ boto and awscli

### CODE REVIEW

**Comment by tkelman** [comment]
It looks like it fixes awscli (which gets further until being broken by #919 instead), but boto3 looks like it's mishandling something
```
2020-03-28 17:23:05,938 INFO     conda_forge_tick.auto_tick || VERSION-Version IS MIGRATING boto3
2020-03-28 17:23:05,938 INFO     github3 || Building a url from ('https://api.github.com', 'rate_limit')
2020-03-28 17:23:05,977 INFO     github3 || JSON was returned
2020-03-28 17:23:05,978 INFO     github3 || Building a url from ('https://api.github.com', 'repos', 'conda-forge', 'boto3-feedstock')
2020-03-28 17:23:05,978 INFO     github3 || Missed the cache building the url
2020-03-28 17:23:06,104 INFO     github3 || JSON was returned
2020-03-28 17:23:06,106 INFO     github3 || Building a url from ('https://api.github.com', 'repos', '*********************', 'boto3-feedstock')
2020-03-28 17:23:06,106 INFO     github3 || Missed the cache building the url
2020-03-28 17:23:06,241 INFO     github3 || JSON was returned
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.~/repo/cf-graph/feedstocks/boto3-feedstock ~/repo/cf-graph
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 1565136 Update to 1.6.1 (#34)
HEAD is now at a29feb2 updated v1.12.30 (#517)
error: pathspec '1.12.31' did not match any file(s) known to git
~/repo/cf-graph
2020-03-28 17:23:08,584 INFO     conda_forge_tick.migrators.version || selector: None
2020-03-28 17:23:08,602 ERROR    conda_forge_tick.auto_tick || NON GITHUB ERROR
Traceback (most recent call last):
  File "/root/repo/cf-scripts/conda_forge_tick/auto_tick.py", line 922, in main
    hash_type=attrs.get("hash_type", "sha256"),
  File "/root/repo/cf-scripts/conda_forge_tick/auto_tick.py", line 166, in run
    migrate_return = migrator.migrate(recipe_dir, feedstock_ctx.attrs, **kwargs)
  File "/root/repo/cf-scripts/conda_forge_tick/migrators/version.py", line 442, in migrate
    cmeta, cmeta.meta[src_key], hash_type,
  File "/root/repo/cf-scripts/conda_forge_tick/migrators/version.py", line 250, in _try_to_update_version
    evaled_context = cmeta.eval_jinja2_exprs(context)
  File "/root/repo/cf-scripts/conda_forge_tick/recipe_parser/_parser.py", line 438, in eval_jinja2_exprs
    jinja2.Template(tmpl).render(**jinja2_vars))
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/main.py", line 341, in load
    return constructor.get_single_data()
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 111, in get_single_data
    node = self.composer.get_single_node()
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/composer.py", line 78, in get_single_node
    document = self.compose_document()
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/composer.py", line 101, in compose_document
    node = self.compose_node(None, None)
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/composer.py", line 218, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/composer.py", line 111, in compose_node
    if self.parser.check_event(AliasEvent):
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/parser.py", line 140, in check_event
    self.current_event = self.state()
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/parser.py", line 600, in parse_block_mapping_value
    if self.scanner.check_token(ValueToken):
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 1764, in check_token
    self._gather_comments()
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 1806, in _gather_comments
    self.fetch_more_tokens()
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 303, in fetch_more_tokens
    return self.fetch_folded()
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 712, in fetch_folded
    self.fetch_block_scalar(style='>')
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 721, in fetch_block_scalar
    self.tokens.append(self.scan_block_scalar(style))
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 1973, in scan_block_scalar
    return Scanner.scan_block_scalar(self, style, rt=rt)
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 1154, in scan_block_scalar
    chomping, increment = self.scan_block_scalar_indicators(start_mark)
  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/ruamel/yaml/scanner.py", line 1299, in scan_block_scalar_indicators
    self.reader.get_mark(),
ruamel.yaml.scanner.ScannerError: while scanning a block scalar
  in "<unicode string>", line 16, column 18:
    botocore_bounds: >=1.15.31,<1.16.0
                     ^ (line: 16)
expected chomping or indentation indicators, but found '='
  in "<unicode string>", line 16, column 19:
    botocore_bounds: >=1.15.31,<1.16.0
                      ^ (line: 16)
```
```

**Comment by beckermr** [comment]
Yup. That is an error in the recipe itself.

**Comment by beckermr** [comment]
The > symbol after a colon is special in yaml. You’ll need quotes if you want a string.

**Comment by beckermr** [comment]
Ohhhh crap. Nope that is my code. I’m very sorry. I will fix and thanks for the bug report!

**Comment by tkelman** [comment]
I could revert https://github.com/conda-forge/boto3-feedstock/commit/4290fb9ba7547185049f4f138aa6f9539f0ac9d4 which was working around an issue with the initial version of the substitution... for now I'll leave the recipes alone since there shouldn't be a new upstream release until Monday.

**Comment by beckermr** [comment]
I just pushed another fix. Thanks for all the help here. Give it a few more tries.

**Comment by hmaarrfk** [comment]
gah, thanks!

**Comment by tkelman** [comment]
Looking okay now. https://github.com/conda-forge/awscli-feedstock/pull/522, https://github.com/conda-forge/boto3-feedstock/pull/518

May want to skim the logs for anything else that might have regressed without the maintainers noticing yet. The aws stack is super obvious since upstream does 1 or 2 new releases almost every weekday.

**Comment by beckermr** [comment]
Yup. I’ve been looking and not seeing anything yet. I’m still learning the jinja2 ast

**Comment by beckermr** [comment]
Thanks for the bug reports!

**Comment by isuruf** [comment]
Maybe we should add `boto3` and `awscli` as test cases

**Comment by beckermr** [comment]
I already added tests for the jinja syntax they use in the right spots. Let me dig up the link

**Comment by beckermr** [comment]
This line and the several above it are the tests. 
https://github.com/regro/cf-scripts/blob/master/tests/test_recipe_parser.py

**Comment by beckermr** [comment]
Stupid phone. Line 29 and above

**Pull request merged**
