### PR TITLE
include cython in compilers

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@mariusvniekerk

**Comment by CJ-Wright** [comment]
This needs to also add compilers.

**Comment by justcalamari** [comment]
Doesn't update-cb3 do that, @CJ-Wright?

**Comment by CJ-Wright** [comment]
I'm not certain. Does it? If not we can add toolchain before `update-cb3` and then have it run and add the compilers.

**Comment by isuruf** [comment]
It does add C compiler, but not C++ compiler. (It's hard to figure out whether C or C++ is needed.)

**Comment by CJ-Wright** [comment]
Should we add both?

**Comment by CJ-Wright** [comment]
I guess we can add a note which states that we've added a c compiler and not a c++ compiler and if the project needs c++ then you should add it.

**Comment by CJ-Wright** [comment]
@scopatz @isuruf @mariusvniekerk @justcalamari I think this is ready for review/merge.

**Comment by CJ-Wright** [comment]
Thank you very much!

**Comment by mariusvniekerk** [comment]
Sadly I don't think this is enough.  Until we use file lists from libcflib we will miss things

**Comment by CJ-Wright** [comment]
That's completely true. I wasn't aiming to get all the missing files, I just wanted to get a lot of the packages. My hope it's to remove some things from that list to make it a bit more manageable. At some point we're going to need to do stuff by hand due to missing toolchain.

**Comment by CJ-Wright** [comment]
This also won't work because I forgot to turn the compilers back on.

**Comment by justcalamari** [comment]
If you're turning the compilers back on, can you release conda-smithy?

**Comment by CJ-Wright** [comment]
maybe, I can't support it if it goes sideways tomorrow.

**Pull request merged**
