### PR TITLE
Run some integration tests

### PR DESCRIPTION
**Pull request by CJ-Wright**
This way we can know if things aren't working.

This may need some integration on the Travis side as well.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
As suspected this needs keys for the bot.

**Comment by CJ-Wright** [comment]
I've added the missing keys. I think this should work now. We need to make certain that we don't push on things. Also we don't want to blow up the GH api.

**Comment by CJ-Wright** [comment]
use dry-run here

**Comment by beckermr** [comment]
closing as this PR is too old to be merged

**Pull request closed without merging**
