### PR TITLE
Pull bot into scripts

### PR DESCRIPTION
**Pull request by ericdill**
per [this comment thread](https://github.com/regro/cf-scripts/pull/1598#discussion_r1096195583) in a different PR and a discussion over elemnt with @beckermr, it seems sensible to try to merge the autotick-bot and cf-scripts repos since once can't really meaningfully move without the other being updated. Seems highly likely that the bot will be down for a bit while this stuff gets sorted out. Hopefully this makes it easier to move the project forward.

TODOs
- [ ] add `${{ secrets.AUTOTICK_BOT_TOKEN }}` to cf-scripts repo
- [ ] revisit `install_bot_code.sh` since it doesn't need to clone the cf-scripts repo any longer
- [ ] anything else?

Notes & Questions
- this was done via copying the non-git files from autotick-bot into cf-scripts. It's absolutely not my intent to claim credit for this work. It would also be feasible to merge the repos and git history together if that's of interest. I didn't initially do that just cause of complexity. If anyone cares about preserving history of the autotick-bot i'm 100% happy to do the git merging necessary to pull in all of the changes into this repo. Just let me know
- Leaving this in draft PR status for now so it doesn't accidentally get merged 🤣

### CODE REVIEW

**Comment by beckermr** [comment]
Right now the pr is going to check out the bot code twice. This might be fine. I'm honestly not sure.

**Comment by ericdill** [comment]
> Right now the pr is going to check out the bot code twice. This might be fine. I'm honestly not sure.

ah yea good call. ill need to look at the install_bot_code.sh script again to update it for this new location

**Comment by beckermr** [comment]
The current code will clone the other repos into the bot repo. I think maybe we should move one directory up in an bunch of spots or adjust the top level actions to clone to a special dir.

**Comment by beckermr** [comment]
This is what the previous autotick bot repo did.

**Comment by beckermr** [comment]
We should be able to merge this one now. Everything is off right now. Once we merge it, we can turn on one job while disabling that job on the other repo and make sure it runs properly. We'll rinse and repeat to move the whole bot over.

**Pull request merged**
