### PR TITLE
add r-base migrator

### PR DESCRIPTION
**Pull request by bgruening**
ping @ocefpaf and @isuruf

### CODE REVIEW

**Comment by ocefpaf** [comment]
This will be the biggest migration since the compilers! :tada:

**Comment by isuruf** [comment]
Doesn't this need a PR to conda-forge-pinning?

**Comment by isuruf** [comment]
@mariusvniekerk, is there a way to wait for an hour or two to issue a PR after a dependency PR has been merged so that the maintainers will not have to restart the builds?

**Comment by ocefpaf** [comment]
I assumed the pinning package was already updated. Sorry.

**Comment by bgruening** [comment]
Sorry, here it is: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/245

**Comment by isuruf** [comment]
Since, there's a discussion in conda-forge-pinning, maybe we should revert this change before the migrator starts issuing lots of PRs.

**Comment by dbast** [comment]
The first opened PRs are stilling building against R3.5.1, e.g. https://github.com/conda-forge/r-rcpp-feedstock/pull/12

**Pull request merged**
