### PR TITLE
Add NVIDIA package source

### PR DESCRIPTION
**Pull request by leofang**
This would save some manual work for several feedstocks:
```python
>>> from conda_forge_tick import update_sources
>>> nv = update_sources.NVIDIA()
>>> nv.next_ver_func('cuda', '11.6.1')
'11.6.2'
>>> nv.next_ver_func('cuda', '11.6.2')
'11.7.0'
>>> nv.next_ver_func('cutensor', '1.4.0')
'1.5.0.3'
>>> nv.next_ver_func('cuquantum', '22.03.0')
'22.05.0.41'
```
A few feedstocks ~~(ex: cuSPARSELt)~~ would require NVIDIA to change the binary archive (which is an ongoing work) but those should not be a blocker for this PR.

Note: I feel this might require some minor changes in the recipes (ex: include the build version in the version string), so let's also discuss necessary changes in this PR.

cc: @jakirkham @kkraus14 @kmittman @jaimergp @beckermr

### CODE REVIEW

**Comment by leofang** [comment]
Question: how does the bot know how to update sha256?

**Comment by beckermr** [comment]
A combination of regex and parsing plus actually downloading and hashing the package. 

I didn't write that bit so others should comment.

**Comment by leofang** [comment]
Note: Once `cudatoolkit` is split (https://github.com/conda-forge/cudatoolkit-feedstock/issues/62) this PR would be a must, otherwise there's too much overhead in updating individual components.

**Comment by leofang** [comment]
@beckermr Could you enable the tests for this PR? 🙂

**Comment by beckermr** [comment]
Done!

**Comment by beckermr** [comment]
If you run pre-commit run -a locally it will fix the check.

**Comment by leofang** [comment]
```python
>>> nv.next_ver_func('cusparselt', '0.2.0')
'0.3.0.3'
```

**Comment by leofang** [comment]
```python
>>> nv.next_ver_func('cusparselt', '0.2.0')
'0.3.0.3'
```

**Comment by leofang** [comment]
Thanks, @beckermr! CI is green now.

All: Am I on the right track? Would this PR be enough for the bot to pick up new version updates for NVIDIA packages?

**Comment by beckermr** [comment]
The tests look ok. Usually the best way is to merge it live and see what happens.

**Comment by leofang** [comment]
Cool. @jakirkham, should we give it a shot? @beckermr Where can I monitor the bot's logs?

**Comment by beckermr** [comment]
The bots logs are at regro/autotick-bot.

**Comment by leofang** [comment]
Thanks, @beckermr! I'll monitor it.

**Comment by leofang** [comment]
It's working now: https://github.com/conda-forge/cutensor-feedstock/pull/32 (cc: @kmittman)

**Pull request merged**
