### PR TITLE
feat: enable cross-compilation by default

### LINKED ISSUE #2930: Switch arch migrator to cross-compilation by default
Given the ongoing issues we have been experiencing with Travis CI ( https://github.com/conda-forge/status/issues/185 ), think we should start using cross-compilation on Azure as the default for new Arch Migrator PRs. This way we start with a configuration that usually works (sometimes with tweaks) while still building about as quickly as a native build

### PR DESCRIPTION
**Pull request by beckermr**
#### Description:

This PR turns on cross-compilation for aarch64+ppc64le by default.

#### Checklist:

- [x] Pydantic model updated or no update needed

#### Cross-refs, links to issues, etc:

closes #2930

### CODE REVIEW

**Comment by beckermr** [comment]
pre-commit.ci autofix

**Comment by beckermr** [comment]
@isuruf can you look at this to make sure the selection of minimigrators I have added makes sense?

**Comment by isuruf** [comment]
The mini-migrators probably should have better filter functions to skip any feedstock that has cross-compilation enabled for some other platform. Applying them the second time is not a no-op. i.e. `f(f(x)) != f(x)`

**Comment by beckermr** [comment]
closing since travis is working

**Pull request closed without merging**
