### PR TITLE
Include test requirements only if we are building that node

### LINKED ISSUE #1331: Migration metadata for dependencies seems off
There has been some anecdotal evidence of the pypy37 migrator opening PRs before all dependencies are built (e.g. pandas was opened without numpy having been built, https://github.com/conda-forge/osqp-feedstock/pull/33 without scipy having been built).

In contrast to numpy, scipy is at least shown under "awaiting parents" on the migrator page, but looking at a "reverse search" of the listed immediate children reveals that the migrator thinks that scipy depends on:
* tbb
* psycopg2
* typed-ast
* pandas

However, the actual [recipe](https://github.com/conda-forge/scipy-feedstock/blob/master/recipe/meta.yaml) depends on none of them!

### PR DESCRIPTION
**Pull request by isuruf**
Fixes #1331

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
Why are we also keeping the build/host here too? I think we can get rid of those as well for nodes we do not build, right?

**Comment by beckermr** [comment]
We can remove those in another PR if we want.

**Comment by beckermr** [comment]
Thanks @isuruf for the clever fix!

**Comment by isuruf** [comment]
> Why are we also keeping the build/host here too? I think we can get rid of those as well for nodes we do not build, right?

Depends on if the code here handles `run_exports` correctly or not.

**Comment by h-vetinari** [comment]
Very cool, thanks!

**Comment by beckermr** [comment]
I think we handle run exports correctly now when building the graph nodes. Or at least we are doing it better than before.

I'll make a PR to remove them and we can see what happens.

**Pull request merged**
