### PR TITLE
ENH check for upstream extensions, fix openssh

### PR DESCRIPTION
**Pull request by beckermr**
Reverts regro/cf-scripts#812

### CODE REVIEW

**Comment by scopatz** [comment]
This looks fine to me!

**Comment by beckermr** [comment]
Great! This one killed the bot a few times. I think it was that I was not streaming urls for hashes. I have restored the old URL hashing for now.

**Comment by CJ-Wright** [comment]
I love the branch name!

**Comment by beckermr** [comment]
And this one killed the bot again. grrrrrrrrrr

**Pull request merged**
