### PR TITLE
ENH let it ship the 10th one if that version is ok

### PR DESCRIPTION
**Pull request by beckermr**
This fixes a bug where if we reach the 10th version in a series, we never ship it.

### CODE REVIEW

**Comment by beckermr** [comment]
It needs some tests.

**Comment by isuruf** [comment]
We can increase the `max_count` and keep this.
I can't exactly which provider (gitlab or bitbucket or inria-forge), but they were returning `master.tar.gz` when the version was non-existent and this resulted in all versions being available. This might be redundant after the sha256 check was added.

**Comment by beckermr** [comment]
This is redundant with the sha checks. 

Increasing the count makes the whole job take longer, so shipping the last one is a decent compromise. 

I need to add tests for this anyways. Thanks for the tips on where to look for the buggy urls. I'll dig a bit there.

**Comment by beckermr** [comment]
It is this url

actual version:

```
$ curl -LI http://spams-devel.gforge.inria.fr/hitcounter2.php?file/38351/spams-2.6.2.5.tar.gz
HTTP/1.1 200 OK
Date: Sat, 13 Feb 2021 12:22:14 GMT
Server: Apache/2.4.10 (Debian)
Vary: Host
Content-Security-Policy: frame-ancestors 'self' gforge.inria.fr *.gforge.inria.fr forge-qualif.inria.fr *.forge-qualif.inria.fr ;
Content-Type: text/html; charset=UTF-8

```

not a real version:

```
$ curl -LI http://spams-devel.gforge.inria.fr/hitcounter2.php?file/38351/spams-3487134325.tar.gz
HTTP/1.1 200 OK
Date: Sat, 13 Feb 2021 12:22:10 GMT
Server: Apache/2.4.10 (Debian)
Vary: Host
Content-Security-Policy: frame-ancestors 'self' gforge.inria.fr *.gforge.inria.fr forge-qualif.inria.fr *.forge-qualif.inria.fr ;
Content-Type: text/html; charset=UTF-8

```

**Comment by beckermr** [comment]
This PR is ready for review and merge. I have added tests of two feedstocks. One is the one above where a new url returns the same hash. I have checked the logs and this is happening and the code properly reports no new version. The second is a feedstock where we get to the 10th version. This test returns the 10th version correctly.

cc @CJ-Wright @isuruf

**Review by CJ-Wright — APPROVED** [review]
LGTM! Thank you very much!

**Comment by beckermr** [comment]
The tests pass locally. Trying again to debug.

**Pull request merged**
