### PR TITLE
add msys2 into the mamba solve

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
cycle for CI

**Comment by CJ-Wright** [comment]
@beckermr I think this will be needed for R

**Comment by beckermr** [comment]
Yup. We should check the rest of the default channels while we are at it and make sure we have them. We might pull them from their source instead of hard coding things.

**Comment by CJ-Wright** [comment]
pushes to this branch welcome!

**Pull request merged**
