### PR TITLE
add stdlib piggyback to version_migrator

### PR DESCRIPTION
**Pull request by h-vetinari**
This was already brought up in #2372, and discussed in today's core call as well (no objection to turning it on despite the limitation about templated output names). Since we haven't had any notable issues I can remember over the last ~2 weeks, I think it's a good time to add it to the version migrator as well now.

Also pick up a drive-by fix for making the sysroot regex pattern catch some more relevant cases.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Interestingly, this breaks a few tests that (presumably) expect nothing to happen:
```
FAILED tests/test_jpeg_libjpeg_turbo.py::test_jpeg_turbo[jpegturbo_pillow_before_meta.yaml-jpegturbo_pillow_after_meta.yaml-9.4.0] - AssertionError: assert {'bot_rerun':...ion': '9.4.0'} == {}
FAILED tests/test_version_migrator.py::test_version_up[numpy-1.24.1] - AssertionError: assert {'bot_rerun':...on': '1.24.1'} == {}
FAILED tests/test_version_migrator.py::test_version_up[python-3.9.5] - AssertionError: assert {'bot_rerun':...ion': '3.9.5'} == {}
```

**Comment by beckermr** [comment]
Those look like bad url requests. Let's rety since I think it is unrelated.

**Comment by beckermr** [comment]
LGTM! 

Shall we merge @h-vetinari?

**Comment by h-vetinari** [comment]
Alright, let's give this a go! 🚀

**Pull request merged**
