### PR TITLE
delete branches of PRs closed for a day or more

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@regro/auto-tick

**Comment by CJ-Wright** [comment]
I think this will allow us to restart our openssl PRs (since we will delete the old branches and make new ones, rather than committing on top of our old ones).

**Comment by mariusvniekerk** [comment]
looks good

**Comment by CJ-Wright** [comment]
Thank you!

**Pull request merged**
