### PR TITLE
Readd Git backend, again

### PR DESCRIPTION
**Pull request by ytausch**
This should resolve the errors we observed in https://github.com/regro/cf-scripts/actions/runs/9465733947/job/26075864527

We erroneously returned the directory name of the feedstock and not the full feedstock path in `get_repo`.

- [x] Pydantic model updated or no update needed

### CODE REVIEW

**Comment by beckermr** [comment]
Is there a better way to test this PR before we merge again?

**Comment by ytausch** [comment]
Problem is, there are no real tests for the `auto_tick` module - and I think it's currently not worth building them because I want to change some more git-related things about it.
Running locally is also not really possible currently. So I guess we should just try again - feel free to review the code again if you think that makes sense.

**Comment by beckermr** [comment]
OK. I will merge this PR when I have a chance to baby sit the bot and see what happens.

**Comment by ytausch** [comment]
Just as a note: I would appreciate if we could use "rebase" instead of "merge" to keep this PR up-to-date with the base branch for now. I have three branches that all depend on this, and rebasing helps me to keep a clean history.

**Comment by ytausch** [comment]
@beckermr I would appreciate if we can merge this finally.

**Pull request merged**
