### PR TITLE
Unify PRed and PRed_json

### LINKED ISSUE #499: eliminate PRed
Just use PRed_json everywhere. This will mean we only reference newer migrations and fixes some other issues we've been running into with the indices not being the same.

### PR DESCRIPTION
**Pull request by CJ-Wright**
Closes #499

### CODE REVIEW

**Comment by CJ-Wright** [comment]
This needs a migration of the graph!

**Comment by mariusvniekerk** [comment]
Fails to generate the test_status

```
Traceback (most recent call last):
  File "/home/travis/mc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/travis/mc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/mc/lib/python3.7/site-packages/conda_forge_tick-0.0.1-py3.7.egg/conda_forge_tick/test_status.py", line 25, in <module>
    main()
  File "/home/travis/mc/lib/python3.7/site-packages/conda_forge_tick-0.0.1-py3.7.egg/conda_forge_tick/test_status.py", line 19, in main
    status, build_order = migrator_status(migrator, gx)
  File "/home/travis/mc/lib/python3.7/site-packages/conda_forge_tick-0.0.1-py3.7.egg/conda_forge_tick/auto_tick.xsh", line 517, in migrator_status
    elif pr_json['PR']['state'] == 'closed':
KeyError: 'PR'
The command "python -m conda_forge_tick.test_status" exited with 1.
```

**Comment by CJ-Wright** [comment]
That is because the graph doesn't have the unified fields yet. This needs a migration first.

**Comment by scopatz** [comment]
So what is the order of operations here?

**Comment by CJ-Wright** [comment]
Approval, stop not, migrate graph, merge PR, start bot

**Comment by scopatz** [comment]
Ahh, do we have code to migrate the graph?

**Comment by CJ-Wright** [comment]
Not yet

**Comment by scopatz** [comment]
Ahh ok :)

**Comment by CJ-Wright** [comment]
I've added a migration script. I think this should happen before the payload PR, since this doesn't use the payload syntax.

**Comment by scopatz** [comment]
migrator looks fine

**Pull request merged**
