### PR TITLE
Revert "Attempt to profiling the auto-tick.py "

### PR DESCRIPTION
**Pull request by CJ-Wright**
Reverts regro/cf-scripts#1071

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@viniciusdc this caused an error https://app.circleci.com/pipelines/github/regro/circle_worker/18359/workflows/ace25a8d-db31-4b20-844a-57d95c2a8437/jobs/36182

**Comment by CJ-Wright** [comment]
I think I fixed it on master

**Comment by viniciusdc** [comment]
the problem arises from:
```python
 File "/root/repo/cf-scripts/conda_forge_tick/auto_tick.py", line 936, in main
    with open(f"profiler/{current_time}.txt", "w+") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'profiler/03-08-2020_23_06_40.txt'
```

**Comment by viniciusdc** [comment]
I think that is odd

**Pull request closed without merging**
