### PR TITLE
use the full graph to run the impact analysis of a pin change

### PR DESCRIPTION
**Pull request by CJ-Wright**
CC: @beckermr

### CODE REVIEW

**Review by beckermr — COMMENTED** [review]
So what I cannot tell from this is if `self.graph` is used in more than one way here. Can we pass in a `full_graph` parameter instead and set a new attribute to make sure nothing else breaks?

**Comment by CJ-Wright** [comment]
Sure, I did try to track down if it is used elsewhere and came up with nothing.

**Comment by beckermr** [comment]
Ahh ok. If you are confident in that then merge away!

**Comment by CJ-Wright** [comment]
I've pushed the requested changes

**Review by beckermr — APPROVED** [review]

**Pull request merged**
