### PR TITLE
More verbose yaml creator

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by beckermr** [comment]
@CJ-Wright do you want to compute the migration size here? I simple loop over the graph looking for the dep should do the trick to get a rough size

**Comment by CJ-Wright** [comment]
I don't really want to do that in the PR body, since it doesn't have access to the graph.

**Comment by CJ-Wright** [comment]
Maybe at that point we should, pull the `add_rebuild_migration_yaml` inner loop into a function that expects a loaded yaml file, pass the graph into the `Create...` migrator init, and then build the appropriate migrator and then do a filter. It's more work but if we're going to go through the effort of increasing the scope of the migrator to hold onto the graph then we might as well get it correct.

**Comment by beckermr** [comment]
Sure or we can pass an approximate count as an argument to the constructor like you did here with the feedstock name.

**Comment by CJ-Wright** [comment]
To be fair that approximate count could be quite removed from the actual count without filtering, for instance the number of packages that list python as a dep is far removed from the number of packages that actually need to be rebuilt.

**Comment by beckermr** [comment]
How so?

**Comment by CJ-Wright** [comment]
Many packages that have a python dep are noarch, which we don't rebuild when we rebuild python.

**Comment by beckermr** [comment]
noarch is a special case

**Comment by CJ-Wright** [comment]
Also packages that are only depended on as a run dependency, not build or host.
Pretty much this entire block of code: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/auto_tick.py#L392-L418

Most likely that block should be lifted into its own function and used.

**Comment by beckermr** [comment]
Sure. That sounds like a good plan for this.

**Comment by beckermr** [comment]
We can call that block to get an approximate count and then feed it in as an argument to go in the pr text.

**Comment by CJ-Wright** [comment]
We still need to have the graph in hand. That wouldn't be an *approximate* count, that would be *the* count, it is what the migrator thinks needs to be migrated.

**Comment by beckermr** [comment]
Right. We have the graph in auto_tick.py when we make the migrators. I’ll make a pr after this one.

**Comment by CJ-Wright** [comment]
Great! I think this will be a good opportunity to pay down technical debt and provide the correct information where possible. The refactor work is most likely out of scope for this PR anyway.
I'll try to put up some refactors around the outputs to feedstock lookup, which should be pulled from the graph where possible (that way we keep everything consistent).

**Comment by CJ-Wright** [comment]
Also in that case, would you like to merge?

**Comment by beckermr** [comment]
Merge Away!

**Pull request merged**
