### PR TITLE
Update jinja var for build if exists

### LINKED ISSUE #94: When build number is a variable, change the variable, not build number
For example, here, no change should happen to build number.
https://github.com/conda-forge/lighttpd-feedstock/pull/1

I guess this should be a general rule: if some value is provided via a variable, change the variable value.

### PR DESCRIPTION
**Pull request by justcalamari**
Closes #94, #21, #32

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@jakirkham I don't think this solves the issue you found completely (since it will overwrite both build numbers), but I think it gets part of the way there.

@justcalamari do you have a link to that issue?

**Comment by CJ-Wright** [comment]
This LGTM, I'll run a dedicated run on travis to see if this works.

**Comment by CJ-Wright** [comment]
@justcalamari thank you very much!

**Comment by justcalamari** [comment]
@CJ-Wright which issue?

**Comment by CJ-Wright** [comment]
There was one that recently came up on a feedstock PR the bot issued. There was a selector associated with the build number.

**Comment by justcalamari** [comment]
Ok I see it. One way to handle this is to only replace the jinja definition if the variable is a number, so `build_number = 2` gets replaced, but not `build_number = build_number + 200`.

**Comment by justcalamari** [comment]
Is there an issue or is it just the PR?

**Comment by CJ-Wright** [comment]
The PR please

**Comment by justcalamari** [comment]
https://github.com/conda-forge/vtk-feedstock/pull/58#discussion_r187773678

**Pull request merged**
