### PR TITLE
Reapply (Git-6) Use new Git Backend in Entire auto_tick flow

### PR DESCRIPTION
**Pull request by ytausch**
#### Description:

This PR reapplies the revert done in https://github.com/regro/cf-scripts/pull/3024.

The error was observed because the HTTP Basic Auth token needs to be base64 encoded.

c54001a65e2d3285cb65578c04abd9d7dcd16379 applies the necessary fix.

#### Checklist:

- [x] Pydantic model updated or no update needed

#### Cross-refs, links to issues, etc:

Cc @pavelzw

### CODE REVIEW

**Review by pavelzw — APPROVED** [review]

**Review by beckermr — APPROVED** [review]
LGTM!

**Comment by beckermr** [comment]
@ytausch we need to revert this one again: See the errors in this job:

https://github.com/regro/cf-scripts/actions/runs/11783101890/job/32819561459

**Comment by ytausch** [comment]
> @ytausch we need to revert this one again: See the errors in this job:
> 
> https://github.com/regro/cf-scripts/actions/runs/11783101890/job/32819561459

I think this is not a functional bug but just confusing log output. Very likely the message is generated by these lines:

https://github.com/regro/cf-scripts/blob/eedaf0f4385aa4f34671836d2e0c4f73918937b3/conda_forge_tick/git_utils.py#L529-L538

(The bot tries to checkout a branch to see if it already exists.)

I can suppress stdout and stderr output for these speculative git invocations, WDYT?

**Comment by beckermr** [comment]
No there is a bug. See here:

```
  2024-11-11 17:21:03,988 ERROR    conda_forge_tick.auto_tick || NON GITHUB ERROR
  Traceback (most recent call last):
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 720, in _run_migrator_on_feedstock_branch
      migrator_uid, pr_json = run_with_tmpdir(
                              ^^^^^^^^^^^^^^^^
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 451, in run_with_tmpdir
      return run(
             ^^^^
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 582, in run
      pr_data = git_backend.create_pull_request(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 941, in create_pull_request
      header_fields = {
                      ^
    File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 942, in <dictcomp>
      k: self._github3_session.last_response_headers[k]
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
    File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/requests/structures.py", line 52, in __getitem__
      return self._store[key.lower()][1]
             ~~~~~~~~~~~^^^^^^^^^^^^^
  KeyError: 'last-modified'
```

**Comment by ytausch** [comment]
Just verified: The GitHub API returns the `Last-Modified` header only if we get a PR with GET, and not when creating one with POST, although the response is otherwise identical. Should not be too hard to fix.

**Pull request merged**
