### PR TITLE
PROD see if we can update the env now

### LINKED ISSUE #1723: Unpin `conda-package-handling` & `distributed`
These were pinned (particularly `conda-package-handling`) as part of resolving issue ( https://github.com/conda-forge/status/issues/134 ). We may want to explore unpinning these. Though it is possible these old issues will remerge (so we should be prepared to repin them if so)

https://github.com/regro/cf-scripts/blob/c1c64e9b7b2aaabbd5bc0b2dd21361cf67905c4f/environment.yml#L15
https://github.com/regro/cf-scripts/blob/c1c64e9b7b2aaabbd5bc0b2dd21361cf67905c4f/environment.yml#L20

cc @beckermr

### PR DESCRIPTION
**Pull request by beckermr**
closes #1723

### CODE REVIEW

**Comment by beckermr** [comment]
@jakirkham do you understand this error from dask

```
tests/test_executors.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../micromamba/envs/cf-scripts/lib/python3.9/contextlib.py:117: in __enter__
    return next(self.gen)
conda_forge_tick/executors.py:64: in executor
    import distributed
../../../micromamba/envs/cf-scripts/lib/python3.9/site-packages/distributed/__init__.py:23: in <module>
    from distributed.actor import Actor, ActorFuture, BaseActorFuture
../../../micromamba/envs/cf-scripts/lib/python3.9/site-packages/distributed/actor.py:13: in <module>
    from distributed.client import Future
../../../micromamba/envs/cf-scripts/lib/python3.9/site-packages/distributed/client.py:115: in <module>
    from distributed.worker import get_client, get_worker, secede
../../../micromamba/envs/cf-scripts/lib/python3.9/site-packages/distributed/worker.py:121: in <module>
    from distributed.worker_memory import (
../../../micromamba/envs/cf-scripts/lib/python3.9/site-packages/distributed/worker_memory.py:55: in <module>
    WorkerDataParameter: TypeAlias = Union[
../../../micromamba/envs/cf-scripts/lib/python3.9/typing.py:243: in inner
    return func(*args, **kwds)
../../../micromamba/envs/cf-scripts/lib/python3.9/typing.py:316: in __getitem__
    return self._getitem(self, parameters)
../../../micromamba/envs/cf-scripts/lib/python3.9/typing.py:421: in Union
    parameters = _remove_dups_flatten(parameters)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

parameters = (collections.abc.MutableMapping[str, object], collections.abc.Callable[[], collections.abc.MutableMapping[str, object]...collections.abc.Callable[..., collections.abc.MutableMapping[str, object]], dict[str, typing.Any]], <class 'NoneType'>)

    def _remove_dups_flatten(parameters):
        """An internal helper for Union creation and substitution: flatten Unions
        among parameters, then remove duplicates.
        """
        # Flatten out Union[Union[...], ...].
        params = []
        for p in parameters:
            if isinstance(p, _UnionGenericAlias):
                params.extend(p.__args__)
            elif isinstance(p, tuple) and len(p) > 0 and p[0] is Union:
                params.extend(p[1:])
            else:
                params.append(p)
        # Weed out strict duplicates, preserving the first of each occurrence.
>       all_params = set(params)
E       TypeError: unhashable type: 'list'

../../../micromamba/envs/cf-scripts/lib/python3.9/typing.py:215: TypeError
```

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Does `params` have a `list` as one of its items?

**Comment by jakirkham** [comment]
Maybe there is a bug in [this type definition]( https://github.com/dask/distributed/blob/9b9f948b8143fee43887a941a3304273beed4a50/distributed/worker_memory.py#L55-L66 )?

**Comment by beckermr** [comment]
I cannot reproduce this on my mac so this is going to be hard to debug. :(

**Comment by beckermr** [comment]
sorry for the noise - automerge gone awry. yes it appears to be the type def

**Comment by beckermr** [comment]
xref: https://github.com/dask/distributed/pull/7957

**Comment by jakirkham** [comment]
No worries. Thanks Matt! 🙏

**Pull request merged**
